title: Code Power
description: My Personal Code Power
author: 春丸
github: https://github.com/hengyoush
about: 我是一名Java程序员, 喜欢探寻技术原理.
disqus_shortname: hengyoush-github-io
google_analytics: UA-XXXXXXXX-Y
avatar_url: /static/img/avatar.jpg

enableTags: true
tagarray: [python, java]

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-github
      link: "https://github.com/hengyoush"

share:
  twitter_username: hengyoush
  fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/
    - text: XML Feed
      url: /feed.xml
    - text: Category
      url: /category/java

url: "https://hengyoush.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
